site_name: Sdklib
site_description: SDK helper library.
site_author: Iván Martín Vedriel

repo_url: https://github.com/ivanprjcts/sdklib

pages:
- Home: index.md
- Tutorial:
    - Writing Your First SDK: tutorial/my-first-sdk.md
- User Guide:
    - Renderers: user-guide/renderers.md
    - Sessions: user-guide/sessions.md
    - Authentication: user-guide/authentication.md
    - Https: user-guide/https.md
- About:
    - Release Notes: about/release-notes.md
    - License: about/license.md


copyright: Copyright &copy; 2016 <a href="https://twitter.com/ivanprojects">Ivanprojects</a>.


